.TH "Core/Inc/spi.h" 3 "Thu Dec 15 2022" "street" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/spi.h \- This file contains all the function prototypes for the \fBspi\&.c\fP file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_SPI3_Init\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SPI_HandleTypeDef \fBhspi3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains all the function prototypes for the \fBspi\&.c\fP file\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2022 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.PP
Definition in file \fBspi\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void MX_SPI3_Init (void)"

.PP
Definition at line \fB30\fP of file \fBspi\&.c\fP\&.
.PP
.nf
31 {
32 
33   /* USER CODE BEGIN SPI3_Init 0 */
34 
35   /* USER CODE END SPI3_Init 0 */
36 
37   /* USER CODE BEGIN SPI3_Init 1 */
38 
39   /* USER CODE END SPI3_Init 1 */
40   hspi3\&.Instance = SPI3;
41   hspi3\&.Init\&.Mode = SPI_MODE_MASTER;
42   hspi3\&.Init\&.Direction = SPI_DIRECTION_1LINE;
43   hspi3\&.Init\&.DataSize = SPI_DATASIZE_8BIT;
44   hspi3\&.Init\&.CLKPolarity = SPI_POLARITY_LOW;
45   hspi3\&.Init\&.CLKPhase = SPI_PHASE_1EDGE;
46   hspi3\&.Init\&.NSS = SPI_NSS_SOFT;
47   hspi3\&.Init\&.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_128;
48   hspi3\&.Init\&.FirstBit = SPI_FIRSTBIT_MSB;
49   hspi3\&.Init\&.TIMode = SPI_TIMODE_DISABLE;
50   hspi3\&.Init\&.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
51   hspi3\&.Init\&.CRCPolynomial = 7;
52   hspi3\&.Init\&.CRCLength = SPI_CRC_LENGTH_DATASIZE;
53   hspi3\&.Init\&.NSSPMode = SPI_NSS_PULSE_ENABLE;
54   if (HAL_SPI_Init(&hspi3) != HAL_OK)
55   {
56     Error_Handler();
57   }
58   /* USER CODE BEGIN SPI3_Init 2 */
59 
60   /* USER CODE END SPI3_Init 2 */
61 
62 }
.fi
.SH "Variable Documentation"
.PP 
.SS "SPI_HandleTypeDef hspi3\fC [extern]\fP"

.PP
Definition at line \fB27\fP of file \fBspi\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for street from the source code\&.
