.TH "STM32L4xx_System_Private_Defines" 3 "Thu Dec 15 2022" "street" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32L4xx_System_Private_Defines \- STM32L4xx_System_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   8000000U"
.br
.ti -1c
.RI "#define \fBMSI_VALUE\fP   4000000U"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   16000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HSE_VALUE   8000000U"
Value of the External oscillator in Hz 
.PP
Definition at line \fB110\fP of file \fBsystem_stm32l4xx\&.c\fP\&.
.SS "#define HSI_VALUE   16000000U"
Value of the Internal oscillator in Hz 
.PP
Definition at line \fB118\fP of file \fBsystem_stm32l4xx\&.c\fP\&.
.SS "#define MSI_VALUE   4000000U"
Value of the Internal oscillator in Hz 
.PP
Definition at line \fB114\fP of file \fBsystem_stm32l4xx\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for street from the source code\&.
